# This is a config for E2B sandbox template.
# You can use template ID (niehp527ge0xaxddxxqa) or template name (lovable-test1) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("lovable-test1") # Sync sandbox
# sandbox = await AsyncSandbox.create("lovable-test1") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('lovable-test1')

team_id = "05cfc65d-12ff-4365-a959-13de108431bf"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "lovable-test1"
template_id = "niehp527ge0xaxddxxqa"
